---
deployment:
  tasks:
    - echo "🧹 Deleting old build folder..."
    - rm -rf public/build
    - echo "📂 Unzipping new build..."
    - unzip -o build.zip -d public/
    - echo "🧼 Deleting zip file after extraction..."
    - rm -f build.zip
    - export COMPOSER_ALLOW_SUPERUSER=1
    # - /opt/cpanel/composer/bin/composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader
    # - php composer.phar install --no-dev --prefer-dist --no-interaction --optimize-autoloader
    # - php artisan migrate --force
    # - php artisan config:cache
    # - php artisan route:cache
    # - php artisan view:cache
    # - php artisan storage:link
